{
 "errors": {},
 "symbols": [
  "xcube_geodb.cli",
  "xcube_geodb.cli.common",
  "xcube_geodb.cli.common.cli_option_traceback",
  "xcube_geodb.cli.common.handle_cli_exception",
  "xcube_geodb.cli.common.new_cli_ctx_obj",
  "xcube_geodb.cli.common.parse_cli_kwargs",
  "xcube_geodb.cli.get_by_bbox",
  "xcube_geodb.cli.get_by_bbox.__author__",
  "xcube_geodb.cli.get_by_bbox.get_by_bbox",
  "xcube_geodb.cli.main",
  "xcube_geodb.cli.main.cli",
  "xcube_geodb.cli.main.cli_option_traceback",
  "xcube_geodb.cli.main.get_by_bbox",
  "xcube_geodb.cli.main.main",
  "xcube_geodb.cli.main.version",
  "xcube_geodb.core",
  "xcube_geodb.core.collections",
  "xcube_geodb.core.collections.Collections",
  "xcube_geodb.core.geodb",
  "xcube_geodb.core.geodb.Collections",
  "xcube_geodb.core.geodb.GEODB_API_DEFAULT_PARAMETERS",
  "xcube_geodb.core.geodb.GeoDBClient",
  "xcube_geodb.core.geodb.GeoDBError",
  "xcube_geodb.core.geodb.LOGGER",
  "xcube_geodb.core.geodb.Message",
  "xcube_geodb.core.message",
  "xcube_geodb.core.message.Message",
  "xcube_geodb.defaults",
  "xcube_geodb.defaults.GEODB_API_DEFAULT_PARAMETERS",
  "xcube_geodb.defaults.GEOSERVER_DEFAULT_PARAMETERS",
  "xcube_geodb.defaults.JSON_VALIDATIONS",
  "xcube_geodb.plugin",
  "xcube_geodb.plugin.GeoDBError",
  "xcube_geodb.plugin.init_plugin",
  "xcube_geodb.version",
  "xcube_geodb.version.version"
 ]
}