{
 "errors": {
  "geopandas.geoseries": {
   "exception": "'NoneType' object has no attribute 'type'",
   "traceback": [
    "Traceback (most recent call last):",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/symbol_exporter/symbol_inspection.py\", line 34, in single_file_extraction",
    "    data = jedi.Script(path=file_name, project=jedi.Project(''.join(top_dir))).complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/helpers.py\", line 488, in wrapper",
    "    return func(self, line, column, *args, **kwargs)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/__init__.py\", line 213, in complete",
    "    return completion.complete()",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/completion.py\", line 169, in complete",
    "    cached_name, completion_names = self._complete_python(leaf)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/completion.py\", line 311, in _complete_python",
    "    completion_names += self._complete_inherited(is_function=False)",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/api/completion.py\", line 428, in _complete_inherited",
    "    if (name.api_type == 'function') == is_function:",
    "  File \"/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jedi/inference/value/klass.py\", line 80, in api_type",
    "    if definition.type == 'funcdef':",
    "AttributeError: 'NoneType' object has no attribute 'type'",
    ""
   ]
  }
 },
 "symbols": [
  "geopandas.GeoDataFrame",
  "geopandas.GeoSeries",
  "geopandas.__version__",
  "geopandas.base",
  "geopandas.base.GeoPandasBase",
  "geopandas.base._array_input",
  "geopandas.base._geo_op",
  "geopandas.base._geo_unary_op",
  "geopandas.base._series_op",
  "geopandas.base._series_unary_op",
  "geopandas.geocode",
  "geopandas.geocode._prepare_geocode_result",
  "geopandas.geocode._throttle_time",
  "geopandas.geocode.geocode",
  "geopandas.geodataframe",
  "geopandas.geodataframe.DEFAULT_GEO_COLUMN_NAME",
  "geopandas.geodataframe.GeoDataFrame",
  "geopandas.geodataframe.GeoPandasBase",
  "geopandas.geodataframe.GeoSeries",
  "geopandas.geodataframe.PY3",
  "geopandas.geodataframe._dataframe_set_geometry",
  "geopandas.geodataframe.plot_dataframe",
  "geopandas.geoseries",
  "geopandas.geoseries.GeoSeries",
  "geopandas.io",
  "geopandas.io.file",
  "geopandas.io.file.GeoDataFrame",
  "geopandas.io.file.read_file",
  "geopandas.io.sql",
  "geopandas.io.sql.GeoDataFrame",
  "geopandas.io.sql.GeoSeries",
  "geopandas.io.sql.read_postgis",
  "geopandas.plotting",
  "geopandas.plotting.__pysal_choro",
  "geopandas.plotting.gencolor",
  "geopandas.plotting.norm_cmap",
  "geopandas.plotting.plot_dataframe",
  "geopandas.plotting.plot_linestring",
  "geopandas.plotting.plot_multilinestring",
  "geopandas.plotting.plot_multipolygon",
  "geopandas.plotting.plot_point",
  "geopandas.plotting.plot_polygon",
  "geopandas.plotting.plot_series",
  "geopandas.read_file",
  "geopandas.read_postgis",
  "geopandas.version",
  "geopandas.version.short_version",
  "geopandas.version.version"
 ]
}